import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col bg-gradient-to-b from-gray-900 to-slate-800 text-white">
        <header className="py-16">
          <h1 className="mb-6 text-center text-5xl font-bold text-primary">
            DWITCH&nbsp;.
          </h1>
        </header>

        <main className="flex-1"></main>

        <footer className="border-t border-gray-800 px-8 py-12">
          <div className="px-8 text-center font-medium">
            <span>Create with ❤️ and 🔥</span>
            <br />
            <span>Powered by XMTP, Livepeer, Superfluid.</span>
          </div>
        </footer>
      </div>
      <Script src="https://buttons.github.io/buttons.js" />
    </div>
  );
}
